[indexing]
batch_size = 64

[vectore_store.qdrant_remote]
url = "http://localhost:6333"
collection_name = "education_domain"
distance = "Cosine"

[vectore_store.qdrant_local]
path = "./data/tmp/qdrant_local"
collection_name = "education_domain"
distance = "Cosine"

[embeddings.bge_m3]
model_name = "BAAI/bge-m3"
device = "cpu"
normalize_embeddings = true
dim = 1024

[embeddings.fake]
dim = 100

[chunking.baseline]
chunk_size = 1000
chunk_overlap = 200
separators = ["\n\n", "\n", ". ", "? ", "! ", " ", ""]
